// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/realtime/v1/realtime.proto

package realtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagQuality int32

const (
	TagQuality_TAG_QUALITY_UNSPECIFIED TagQuality = 0
	TagQuality_TAG_QUALITY_GOOD        TagQuality = 1
	TagQuality_TAG_QUALITY_STALE       TagQuality = 2
	TagQuality_TAG_QUALITY_BAD         TagQuality = 3
)

// Enum value maps for TagQuality.
var (
	TagQuality_name = map[int32]string{
		0: "TAG_QUALITY_UNSPECIFIED",
		1: "TAG_QUALITY_GOOD",
		2: "TAG_QUALITY_STALE",
		3: "TAG_QUALITY_BAD",
	}
	TagQuality_value = map[string]int32{
		"TAG_QUALITY_UNSPECIFIED": 0,
		"TAG_QUALITY_GOOD":        1,
		"TAG_QUALITY_STALE":       2,
		"TAG_QUALITY_BAD":         3,
	}
)

func (x TagQuality) Enum() *TagQuality {
	p := new(TagQuality)
	*p = x
	return p
}

func (x TagQuality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagQuality) Descriptor() protoreflect.EnumDescriptor {
	return file_api_realtime_v1_realtime_proto_enumTypes[0].Descriptor()
}

func (TagQuality) Type() protoreflect.EnumType {
	return &file_api_realtime_v1_realtime_proto_enumTypes[0]
}

func (x TagQuality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagQuality.Descriptor instead.
func (TagQuality) EnumDescriptor() ([]byte, []int) {
	return file_api_realtime_v1_realtime_proto_rawDescGZIP(), []int{0}
}

type StreamTagValuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamTagValuesRequest) Reset() {
	*x = StreamTagValuesRequest{}
	mi := &file_api_realtime_v1_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamTagValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamTagValuesRequest) ProtoMessage() {}

func (x *StreamTagValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_realtime_v1_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamTagValuesRequest.ProtoReflect.Descriptor instead.
func (*StreamTagValuesRequest) Descriptor() ([]byte, []int) {
	return file_api_realtime_v1_realtime_proto_rawDescGZIP(), []int{0}
}

type TagValue struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	EquipmentId uint64                 `protobuf:"varint,1,opt,name=equipment_id,json=equipmentId,proto3" json:"equipment_id,omitempty"`
	TagId       uint64                 `protobuf:"varint,2,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*TagValue_BoolValue
	//	*TagValue_IntValue
	//	*TagValue_UintValue
	//	*TagValue_FloatValue
	//	*TagValue_DoubleValue
	//	*TagValue_StringValue
	Value   isTagValue_Value `protobuf_oneof:"value"`
	Quality TagQuality       `protobuf:"varint,9,opt,name=quality,proto3,enum=middleware.realtime.v1.TagQuality" json:"quality,omitempty"`
	// Zero means that this tag has never been read successfully.
	LastSuccessfulReadUnixNano int64 `protobuf:"varint,10,opt,name=last_successful_read_unix_nano,json=lastSuccessfulReadUnixNano,proto3" json:"last_successful_read_unix_nano,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *TagValue) Reset() {
	*x = TagValue{}
	mi := &file_api_realtime_v1_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagValue) ProtoMessage() {}

func (x *TagValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_realtime_v1_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagValue.ProtoReflect.Descriptor instead.
func (*TagValue) Descriptor() ([]byte, []int) {
	return file_api_realtime_v1_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *TagValue) GetEquipmentId() uint64 {
	if x != nil {
		return x.EquipmentId
	}
	return 0
}

func (x *TagValue) GetTagId() uint64 {
	if x != nil {
		return x.TagId
	}
	return 0
}

func (x *TagValue) GetValue() isTagValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TagValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*TagValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *TagValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*TagValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *TagValue) GetUintValue() uint64 {
	if x != nil {
		if x, ok := x.Value.(*TagValue_UintValue); ok {
			return x.UintValue
		}
	}
	return 0
}

func (x *TagValue) GetFloatValue() float32 {
	if x != nil {
		if x, ok := x.Value.(*TagValue_FloatValue); ok {
			return x.FloatValue
		}
	}
	return 0
}

func (x *TagValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*TagValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *TagValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*TagValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *TagValue) GetQuality() TagQuality {
	if x != nil {
		return x.Quality
	}
	return TagQuality_TAG_QUALITY_UNSPECIFIED
}

func (x *TagValue) GetLastSuccessfulReadUnixNano() int64 {
	if x != nil {
		return x.LastSuccessfulReadUnixNano
	}
	return 0
}

type isTagValue_Value interface {
	isTagValue_Value()
}

type TagValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type TagValue_IntValue struct {
	IntValue int64 `protobuf:"zigzag64,4,opt,name=int_value,json=intValue,proto3,oneof"`
}

type TagValue_UintValue struct {
	UintValue uint64 `protobuf:"varint,5,opt,name=uint_value,json=uintValue,proto3,oneof"`
}

type TagValue_FloatValue struct {
	FloatValue float32 `protobuf:"fixed32,6,opt,name=float_value,json=floatValue,proto3,oneof"`
}

type TagValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,7,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type TagValue_StringValue struct {
	StringValue string `protobuf:"bytes,8,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*TagValue_BoolValue) isTagValue_Value() {}

func (*TagValue_IntValue) isTagValue_Value() {}

func (*TagValue_UintValue) isTagValue_Value() {}

func (*TagValue_FloatValue) isTagValue_Value() {}

func (*TagValue_DoubleValue) isTagValue_Value() {}

func (*TagValue_StringValue) isTagValue_Value() {}

var File_api_realtime_v1_realtime_proto protoreflect.FileDescriptor

const file_api_realtime_v1_realtime_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/realtime/v1/realtime.proto\x12\x16middleware.realtime.v1\"\x18\n" +
	"\x16StreamTagValuesRequest\"\x9d\x03\n" +
	"\bTagValue\x12!\n" +
	"\fequipment_id\x18\x01 \x01(\x04R\vequipmentId\x12\x15\n" +
	"\x06tag_id\x18\x02 \x01(\x04R\x05tagId\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValue\x12\x1d\n" +
	"\tint_value\x18\x04 \x01(\x12H\x00R\bintValue\x12\x1f\n" +
	"\n" +
	"uint_value\x18\x05 \x01(\x04H\x00R\tuintValue\x12!\n" +
	"\vfloat_value\x18\x06 \x01(\x02H\x00R\n" +
	"floatValue\x12#\n" +
	"\fdouble_value\x18\a \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\b \x01(\tH\x00R\vstringValue\x12<\n" +
	"\aquality\x18\t \x01(\x0e2\".middleware.realtime.v1.TagQualityR\aquality\x12B\n" +
	"\x1elast_successful_read_unix_nano\x18\n" +
	" \x01(\x03R\x1alastSuccessfulReadUnixNanoB\a\n" +
	"\x05value*k\n" +
	"\n" +
	"TagQuality\x12\x1b\n" +
	"\x17TAG_QUALITY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TAG_QUALITY_GOOD\x10\x01\x12\x15\n" +
	"\x11TAG_QUALITY_STALE\x10\x02\x12\x13\n" +
	"\x0fTAG_QUALITY_BAD\x10\x032{\n" +
	"\x12RealtimeTagService\x12e\n" +
	"\x0fStreamTagValues\x12..middleware.realtime.v1.StreamTagValuesRequest\x1a .middleware.realtime.v1.TagValue0\x01B'Z%middleware/api/realtime/v1;realtimev1b\x06proto3"

var (
	file_api_realtime_v1_realtime_proto_rawDescOnce sync.Once
	file_api_realtime_v1_realtime_proto_rawDescData []byte
)

func file_api_realtime_v1_realtime_proto_rawDescGZIP() []byte {
	file_api_realtime_v1_realtime_proto_rawDescOnce.Do(func() {
		file_api_realtime_v1_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_realtime_v1_realtime_proto_rawDesc), len(file_api_realtime_v1_realtime_proto_rawDesc)))
	})
	return file_api_realtime_v1_realtime_proto_rawDescData
}

var file_api_realtime_v1_realtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_realtime_v1_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_realtime_v1_realtime_proto_goTypes = []any{
	(TagQuality)(0),                // 0: middleware.realtime.v1.TagQuality
	(*StreamTagValuesRequest)(nil), // 1: middleware.realtime.v1.StreamTagValuesRequest
	(*TagValue)(nil),               // 2: middleware.realtime.v1.TagValue
}
var file_api_realtime_v1_realtime_proto_depIdxs = []int32{
	0, // 0: middleware.realtime.v1.TagValue.quality:type_name -> middleware.realtime.v1.TagQuality
	1, // 1: middleware.realtime.v1.RealtimeTagService.StreamTagValues:input_type -> middleware.realtime.v1.StreamTagValuesRequest
	2, // 2: middleware.realtime.v1.RealtimeTagService.StreamTagValues:output_type -> middleware.realtime.v1.TagValue
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_realtime_v1_realtime_proto_init() }
func file_api_realtime_v1_realtime_proto_init() {
	if File_api_realtime_v1_realtime_proto != nil {
		return
	}
	file_api_realtime_v1_realtime_proto_msgTypes[1].OneofWrappers = []any{
		(*TagValue_BoolValue)(nil),
		(*TagValue_IntValue)(nil),
		(*TagValue_UintValue)(nil),
		(*TagValue_FloatValue)(nil),
		(*TagValue_DoubleValue)(nil),
		(*TagValue_StringValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_realtime_v1_realtime_proto_rawDesc), len(file_api_realtime_v1_realtime_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_realtime_v1_realtime_proto_goTypes,
		DependencyIndexes: file_api_realtime_v1_realtime_proto_depIdxs,
		EnumInfos:         file_api_realtime_v1_realtime_proto_enumTypes,
		MessageInfos:      file_api_realtime_v1_realtime_proto_msgTypes,
	}.Build()
	File_api_realtime_v1_realtime_proto = out.File
	file_api_realtime_v1_realtime_proto_goTypes = nil
	file_api_realtime_v1_realtime_proto_depIdxs = nil
}
