// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/realtime/v1/realtime.proto

package realtimev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RealtimeTagService_StreamTagValues_FullMethodName = "/middleware.realtime.v1.RealtimeTagService/StreamTagValues"
)

// RealtimeTagServiceClient is the client API for RealtimeTagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// RealtimeTagService exposes the latest values read from the PLCs.
type RealtimeTagServiceClient interface {
	// StreamTagValues sends the current cache and then only values that change.
	StreamTagValues(ctx context.Context, in *StreamTagValuesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TagValue], error)
}

type realtimeTagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRealtimeTagServiceClient(cc grpc.ClientConnInterface) RealtimeTagServiceClient {
	return &realtimeTagServiceClient{cc}
}

func (c *realtimeTagServiceClient) StreamTagValues(ctx context.Context, in *StreamTagValuesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TagValue], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RealtimeTagService_ServiceDesc.Streams[0], RealtimeTagService_StreamTagValues_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamTagValuesRequest, TagValue]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RealtimeTagService_StreamTagValuesClient = grpc.ServerStreamingClient[TagValue]

// RealtimeTagServiceServer is the server API for RealtimeTagService service.
// All implementations must embed UnimplementedRealtimeTagServiceServer
// for forward compatibility.
//
// RealtimeTagService exposes the latest values read from the PLCs.
type RealtimeTagServiceServer interface {
	// StreamTagValues sends the current cache and then only values that change.
	StreamTagValues(*StreamTagValuesRequest, grpc.ServerStreamingServer[TagValue]) error
	mustEmbedUnimplementedRealtimeTagServiceServer()
}

// UnimplementedRealtimeTagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRealtimeTagServiceServer struct{}

func (UnimplementedRealtimeTagServiceServer) StreamTagValues(*StreamTagValuesRequest, grpc.ServerStreamingServer[TagValue]) error {
	return status.Error(codes.Unimplemented, "method StreamTagValues not implemented")
}
func (UnimplementedRealtimeTagServiceServer) mustEmbedUnimplementedRealtimeTagServiceServer() {}
func (UnimplementedRealtimeTagServiceServer) testEmbeddedByValue()                            {}

// UnsafeRealtimeTagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RealtimeTagServiceServer will
// result in compilation errors.
type UnsafeRealtimeTagServiceServer interface {
	mustEmbedUnimplementedRealtimeTagServiceServer()
}

func RegisterRealtimeTagServiceServer(s grpc.ServiceRegistrar, srv RealtimeTagServiceServer) {
	// If the following call panics, it indicates UnimplementedRealtimeTagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RealtimeTagService_ServiceDesc, srv)
}

func _RealtimeTagService_StreamTagValues_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamTagValuesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RealtimeTagServiceServer).StreamTagValues(m, &grpc.GenericServerStream[StreamTagValuesRequest, TagValue]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RealtimeTagService_StreamTagValuesServer = grpc.ServerStreamingServer[TagValue]

// RealtimeTagService_ServiceDesc is the grpc.ServiceDesc for RealtimeTagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RealtimeTagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "middleware.realtime.v1.RealtimeTagService",
	HandlerType: (*RealtimeTagServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamTagValues",
			Handler:       _RealtimeTagService_StreamTagValues_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/realtime/v1/realtime.proto",
}
